# john jozwiak on 2020 Jun 20

all:	
	( cd detectclones ; make )
	-@make showfiles

test:	
	( cd detectclones ; make test )
	-@make showfiles

clean:	
	( cd detectclones ; make clean )
	-@make showfiles

showfiles:	
	-@echo
	-@/bin/ls -F
	-@echo
